# Nombre del workflow
name: Deploy to VPS with Password

# Disparador: se ejecuta cada vez que haces un push a la rama 'main'
on:
  push:
    branches:
      - main

# Tareas (jobs) a ejecutar
jobs:
  deploy:
    # El tipo de máquina virtual donde se ejecutará el workflow
    runs-on: ubuntu-latest

    # Pasos del workflow
    steps:
      # 1. Clona el código de tu repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Asegurar que el directorio del proyecto exista en la VPS
      - name: Ensure project directory exists on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }} # Se cambia 'key' por 'password'
          script: |
            # Crea el directorio si no existe.
            sudo mkdir -p /var/www/storeverzusfront
            # Asigna la propiedad del directorio al usuario de despliegue.
            sudo chown -R ${{ secrets.VPS_USER }}:${{ secrets.VPS_USER }} /var/www/storeverzusfront

      # 3. Copia los archivos del proyecto a la VPS usando SCP
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }} # Se cambia 'key' por 'password'
          source: "."
          target: "/var/www/storeverzusfront"