# Nombre del workflow
name: Deploy to VPS

# Disparador: se ejecuta cada vez que haces un push a la rama 'main'
on:
  push:
    branches:
      - main

# Tareas (jobs) a ejecutar
jobs:
  deploy:
    # El tipo de máquina virtual donde se ejecutará el workflow
    runs-on: ubuntu-latest

    # Pasos del workflow
    steps:
      # 1. Clona el código de tu repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Copia los archivos del proyecto a la VPS usando SCP
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: "." # Copia todo el contenido del repositorio
          target: ${{ secrets.VPS_PROJECT_PATH }}